/* GENERATED by scripts/stamp-legacy.mjs — do not edit by hand.
   Content hashes of the legacy scripts, used to cache-bust their URLs. */
export const LEGACY_V = {
  "hermes-dock": "d4930caf",
  "hermes-config": "e3d63a83",
  "uc-demo": "7cbfc9eb"
} as const;
