/* GENERATED by scripts/stamp-legacy.mjs — do not edit by hand.
   Content hashes of the legacy scripts, used to cache-bust their URLs. */
export const LEGACY_V = {
  "hermes-dock": "79274beb",
  "hermes-config": "7f30a499",
  "uc-demo": "7cbfc9eb"
} as const;
