/* GENERATED by scripts/stamp-legacy.mjs — do not edit by hand.
   Content hashes of the legacy scripts, used to cache-bust their URLs. */
export const LEGACY_V = {
  "hermes-dock": "c5506f89",
  "hermes-config": "7f30a499",
  "uc-demo": "d047cc48",
  "sl-bar": "0dc94e13"
} as const;
